version: '3.9'

services:
  frontapp:
    container_name: aircnc_front
    restart: always
    command: npm run dev
    ports:
      - 5173:5173
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
